Implementation of a quality indicator after the name
wofsauge/External-Item-Descriptions pull request #106
Opened 2021-05-27 03:04 UTC by Mrashes

@wofsauge Implemented it as a number next to the name (its togglable if the user doesn't like it).  That said, I was unsure if this was the official quality as its coming from a lookup table.

Any feedback is appreciated, as I mentioned, first time with lua

2021-05-27 11:35 UTC, wofsauge requested changes
generally good implementation, but has some flaws

2021-05-27 11:35 UTC, wofsauge commented on main.lua
> +		local withQual = curName
Why a new variable? just overwrite "curName" directly

2021-05-27 11:35 UTC, wofsauge commented on main.lua
> +		local quality = EID.itemWeightsLookup[tonumber(desc.ID)]
that will throw errors on modded items. Lookup table is fine, but should be avoided when modded items are potential targets. So please read the quality from the game directly: https://wofsauge.github.io/IsaacDocs/rep/ItemConfig_Item/#quality

2021-05-27 11:35 UTC, wofsauge commented on eid_config.lua
> +	["ShowQuality"] = true
this new option also needs to be added to the default config at the bottom of the config file.

It also needs a new mod menu entry (just copy paste stuff around in the mod config menu file ;) )

2021-05-27 12:50 UTC, LuanRoger commented
@wofsauge Is it possible to create an interpreter that would receive the quality number and return a string according to the quality (int)?
Like:
0 = Common 
1 = Rare etc

I think it would be better.

2021-05-27 13:26 UTC, wofsauge commented
> @wofsauge Is it possible to create an interpreter that would receive the quality number and return a string according to the quality (int)?
> Like:
> 0 = Common
> 1 = Rare etc
> 
> I think it would be better.

My prefered way would be to have some icon for each quality. Text would be cool too i think...

How about an option to switch between display modes as well?

2021-05-27 14:18 UTC, LuanRoger commented
> > @wofsauge Is it possible to create an interpreter that would receive the quality number and return a string according to the quality (int)?
> > Like:
> > 0 = Common
> > 1 = Rare etc
> > 
> > I think it would be better.
> 
> My prefered way would be to have some icon for each quality. Text would be cool too i think...
> 
> How about an option to switch between display modes as well?
> 

I could do it by text because it has the option of putting color markup like {{Yellow}} or {{Rainbow}}, like Terraria :)
But of course there could be an option to switch between them.

2021-05-27 15:38 UTC, wofsauge commented
> > > @wofsauge Is it possible to create an interpreter that would receive the quality number and return a string according to the quality (int)?
> > > Like:
> > > 0 = Common
> > > 1 = Rare etc
> > > I think it would be better.
> > 
> > 
> > My prefered way would be to have some icon for each quality. Text would be cool too i think...
> > How about an option to switch between display modes as well?
> 
> I could do it by text because it has the option of putting color markup like {{Yellow}} or {{Rainbow}}, like Terraria :)
> But of course there could be an option to switch between them.

What colors and names would you assign to the qualities?
maybe like the WoW item quality system:
0 = Common = gray
1 = Uncommon = green
2 = Rare = blue
3 = Epic = purple
4 = Legendary = orange

(the names sound very dramatic and dont really represent what they mean in isaac environment imo :D )

2021-05-27 17:18 UTC, LuanRoger commented
It's hard to say, but I think it's good to start (even not representing Issac), this is something that can be improved with ideas and suggestions from the community.

2021-05-27 22:23 UTC, wofsauge commented
![image](https://user-images.githubusercontent.com/245725/119904485-c6e03680-bf4a-11eb-9c23-1bff45c13f89.png)
Ive added 5 icons for quality now that you can use if you want.

Icon names are {{Quality0}} to {{Quality4}}

2021-05-28 03:37 UTC, Mrashes commented
Oh sweet, that looks amazing.  I don't have bandwidth today but will try to get it by Saturday.

2021-05-29 18:23 UTC, Mrashes commented on main.lua
> +		local withQual = curName
Came from wanting immutability but based on your implementation I'll refine

2021-05-29 18:49 UTC, Mrashes commented
Adjustments implemented.  Should be better

2021-05-29 18:58 UTC, Mrashes commented
On play testing, it now shows quality for all instances (sac room, cards, pills)  Do we want it to be this way or should I limit it?

2021-05-29 19:13 UTC, Mrashes commented
also more of a bug.  With key begger and samsons ball next to each other its using different icons for quality.  unsure why

2021-05-29 21:57 UTC, merged