Big update to en_us.lua (ab+)
wofsauge/External-Item-Descriptions pull request #589
Opened 2023-10-14 20:19 UTC by Mirades

- Added a lot of icons
- Changed the stat format slightly (made it consistent too)
- Updated upper/lower letter case
- More consistent wording (for example: drop/spawn and fire/shoot and shots/tears)
- Changed the order of stat increases and pickups to be consistent*
- Changed some descriptions

*oriented myself at this list:
↑ Life
↑ Health
↑ Empty heart container
↑ Damage (depending on the item: if the multiplier has impact on the damage up; first flat damage, then multiplier, if not; swap it) ↑ Tears
↑ Fire rate
↑ Tear delay (AB+)
↑ Range
↑ Tear height (AB+)
↑ Shot speed
↑ Tear size
↑ Speed
↑ Luck
↑ Size
↑ Bomb damage
↓ Negative stats in the same order
Heal
+ random, Red, Soul, Black, Eternal, Bone Hearts
+ Coins
+ Bombs
+ Keys
+ Rune
+ Card
+ Pill
+ Devil, Angel chance main tear effect
main other effect
other effects
special conditions: starting again from top

PS: en_us.lua (rep) will get the same updates

2023-10-15 12:00 UTC, Mirades commented
new order orientation:

↑ Life
↑ Health
↑ Empty heart container
↑ Speed
↑ Tears
↑ Fire rate (REP)
↑ Tear delay (AB+)
↑ Damage (depending on the item: if the multiplier has impact on the damage up; first flat damage, then multiplier, if not; swap it)
↑ Range
↑ Tear height (AB+)
↑ Shot speed
↑ Luck
↑ Tear size
↑ Size
↑ Bomb damage
↓ Negative stats in the same order
Heal
+ random, Red, Soul, Black, Eternal, Bone Hearts
+ Coins
+ Bombs
+ Keys
+ Rune
+ Card
+ Pill
+ Devil, Angel chance
main tear effect
main other effect
other effects
special conditions: starting again from top

2023-10-19 05:39 UTC, Mirades commented
Github doesn't handle the 2 items i've removed well (Experimental Treatment and Toxic Shock).
It shows like 10-20 lines as completely rewritten...

Btw I've added the extra line for Car Battery effect that got implemented in the meantime.

2023-10-21 06:15 UTC, Mirades commented
done with the big en_us.lua update.

feel free to discuss the changes with me, i'm active on discord (just ping me @Mirades).

2023-10-22 17:04 UTC, wofsauge commented on descriptions/ab+/en_us.lua
> +	{"228", "Mom's Perfume", "↑ {{Tears}} -1 Tear delay#{{Fear}} 15% chance to shoot fear tears#{{Luck}} 100% chance at 85 luck"},
{{Luck}} 100% chance at 85 luck"
those look to me like useless information for the average player

2023-10-22 18:39 UTC, wofsauge requested changes
Please fix the commented issues,

ALSO:
revert the change of the "{{Warning}}" markup to "!!!". Using "{{Warning}}" is easier for new translators to identify as Markup relevant content, which makes it less likely for them to delete those.

2023-10-22 18:39 UTC, wofsauge commented on descriptions/rep/en_us.lua
> +	[218] = {"218", "Placenta", "↑ {{Heart}} +1 Health#{{Heart}} Heals 1 heart#{{HalfHeart}} 50 chance to heal half a heart every minute"}, -- Placenta
"%" is missing

2023-10-22 18:39 UTC, wofsauge commented on descriptions/rep/en_us.lua
> +	[375] = {"375", "Host Hat", "Immune to explosions and falling projectiles#25% chance to reflect enemy shots"}, -- Host Hat
Same as in AB+: i like the old description better

2023-10-22 18:39 UTC, wofsauge commented on descriptions/rep/en_us.lua
> +	[514] = {"514", "Broken Modem", "Causes some enemies and projectiles to briefly pause at random intervals#Paused projectiles disappear#25% chance to double room clear rewards#(Doesn't double chest,
Same issue as in AB+

2023-10-22 18:39 UTC, wofsauge commented on descriptions/rep/en_us.lua
> +	[577] = {"577", "Damocles", "!!! SINGLE USE !!!#Hangs a sword above Isaac's head, which doubles all pedestal items#Does not double shop, chest, or devil deal items#!!! After taking any damage, the s
0.133 seconds is way to specific and not really "graspable" for every player. Frame is more understandable i think

2023-10-22 18:39 UTC, wofsauge commented on descriptions/rep/en_us.lua
> +	[480] = "Middle ring wisp#Only spawns a wisp if at least one pickup got converted#Increased HP for each pickup converted", -- Compost
change order of informations, to first show the HP increase, and then the limitations

2023-10-26 17:37 UTC, merged